<?php

/**
 * @file
 * Primary module hooks for ONLYOFFICE Connector module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\file\Entity\File;
use Drupal\onlyoffice_connector\OnlyofficeDocumentHelper;
use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function onlyoffice_connector_theme($existing, $type, $theme, $path) {
  return [
    'onlyoffice_editor' => [
      'variables' => [
          'filename' => 'noname',
          'doc_type' => 'docx',
          'doc_server_url' => 'http://127.0.0.1/',
          'config' => '{}',
          'forms_unavailable_notice' => ''
        ],
    ],
  ];
}

/**
 * Implements hook_entity_operation().
 */
function onlyoffice_connector_entity_operation(EntityInterface $entity) {
  if ($entity->getEntityTypeId() != "media" || $entity->bundle() != "document") {
    return null;
  }

  $account = \Drupal::currentUser()->getAccount();

  if (!$entity->access("view", $account)) {
    return null;
  }

  $file = $entity->get(OnlyofficeDocumentHelper::getSourceFieldName($entity))->entity;
  $extension = OnlyofficeDocumentHelper::getExtension($file->getFilename());

  if (OnlyofficeDocumentHelper::getDocumentType($extension) == null) {
    return null;
  }

  $title = "View in ONLYOFFICE";

  if (OnlyofficeDocumentHelper::isEditable($extension) && $entity->access("update", $account)) {
    $title =  "Edit in ONLYOFFICE";
  }

  if (OnlyofficeDocumentHelper::isFillForms($extension) && $entity->access("update", $account)) {
    $title =  "Fill in form in ONLYOFFICE";
  }

  $route_name = "onlyoffice_connector.editor";
  $route_parameters = [
    'media' => $entity->id(),
  ];

  return [
    'onlyoffice' => [
      'title' => $title,
      'weight' => 50,
      'url' => Url::fromRoute($route_name, $route_parameters),
    ],
  ];
}
