<?php

/**
 * @file
 * Primary module hooks for ONLYOFFICE Connector module.
 */

function onlyoffice_connector_theme($existing, $type, $theme, $path) {
  return [
    'onlyoffice_editor' => [
      'variables' => [
          'filename' => 'noname',
          'doc_type' => 'docx',
          'doc_server_url' => 'http://127.0.0.1/',
          'config' => '{}',
          'forms_unavailable_notice' => ''
        ],
    ],
  ];
}