<?php
/**
 *
 * (c) Copyright Ascensio System SIA 2022
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

/**
 * @file
 * Primary module hooks for ONLYOFFICE Connector module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\onlyoffice_connector\OnlyofficeDocumentHelper;
use Drupal\onlyoffice_connector\OnlyofficeAppConfig;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\onlyoffice_connector\OnlyofficeUrlHelper;

/**
 * Implements hook_help().
 */
function onlyoffice_connector_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.onlyoffice_connector':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('????????????????') . '</p>';


      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<p>' . t('????????????????') . '</p>';

      return $output;
  }
}

/**
 * Implements hook_theme().
 */
function onlyoffice_connector_theme($existing, $type, $theme, $path) {
  return [
    'onlyoffice_editor' => [
      'variables' => [
          'filename' => 'noname',
          'doc_type' => 'docx',
          'doc_server_url' => 'http://127.0.0.1/',
          'config' => '{}',
          'error' => null
        ],
    ],
  ];
}

/**
 * Implements hook_entity_operation().
 */
function onlyoffice_connector_entity_operation(EntityInterface $entity) {
  if ($entity->getEntityTypeId() != "media") {
    return null;
  }
  /** @var \Drupal\media\Entity\Media $media */
  $media = $entity;

  if ($media->getSource()->getPluginId() != "file"){
    return null;
  }

  $account = \Drupal::currentUser()->getAccount();

  if (!$media->access("view", $account)) {
    return null;
  }

  $file = $media->get(OnlyofficeDocumentHelper::getSourceFieldName($media))->entity;
  $extension = OnlyofficeDocumentHelper::getExtension($file->getFilename());

  if (OnlyofficeDocumentHelper::getDocumentType($extension) == null) {
    return null;
  }

  $title = t("View in ONLYOFFICE");

  if (OnlyofficeDocumentHelper::isEditable($media) && $media->access("update", $account)) {
    $title =  t("Edit in ONLYOFFICE");
  }

  if (OnlyofficeDocumentHelper::isFillForms($media) && $media->access("update", $account)) {
    $title =  t("Fill in form in ONLYOFFICE");
  }

  return [
    'onlyoffice' => [
      'title' => $title,
      'weight' => 50,
      'url' => OnlyofficeUrlHelper::getEditorUrl($media),
    ],
  ];
}

/**
 * Implements hook_library_info_build().
 */
function onlyoffice_connector_library_info_build() {

  $options = \Drupal::config('onlyoffice_connector.settings');

  if ($doc_server_url = $options->get('doc_server_url')) {
    $api_url = $doc_server_url . OnlyofficeAppConfig::getDocServiceApiUrl();
    return [
      'onlyoffice.api' => [
        'js' => [
          $api_url => [],
        ],
      ],
    ];
  }
}
