name: Artifact

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]
    branches: [main]

jobs:
  artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Info
        run: |
          echo "version=$(grep -Eo '[0-9]+(\.[0-9]+)+' CHANGELOG.md | head -n 1)" >> $GITHUB_OUTPUT
        id: info
      - name: Build Artifact
        run: |
          cd ${{ github.workspace }}
          mkdir -p ./deploy/onlyoffice-drupal
          rsync -av --exclude='deploy' ./ ./deploy/onlyoffice-drupal
          cd ./deploy/onlyoffice-drupal
          rm -rf ./.github/
          rm -rf ./.git/
          rm ./.gitignore
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: onlyoffice-drupal-${{ steps.info.outputs.version }}
          path: deploy
