name: Artifact

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]
    branches: [main]

jobs:
  artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Info
        run: |
          echo "version=$(grep -Eo '[0-9]+(\.[0-9]+)+' CHANGELOG.md | head -n 1)" >> $GITHUB_OUTPUT
        id: info
      - name: Build Artifact
        run: |
          cd ${{ github.workspace }}
          git submodule update --init --recursive
          mkdir -p ./deploy/onlyoffice-drupal
          rsync -av --exclude='deploy' ./ ./deploy/onlyoffice-drupal
          cd ./deploy/onlyoffice-drupal
          rm -rf ./.github/
          rm -rf ./.git/
          rm -rf ./licenses/
          rm ./assets/document-templates/AUTHORS.md
          rm ./assets/document-templates/LICENSE
          rm ./assets/document-templates/README.md
          rm ./.csscomb.json
          rm ./.editorconfig
          rm ./.gitignore
          rm ./.gitmodules
          rm ./3rd-Party.license
          rm ./captainhook.json
          rm ./composer.lock
          rm ./LICENSE
          rm ./phpcs.xml.dist
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: onlyoffice-drupal-${{ steps.info.outputs.version }}
          path: deploy
