name: Lint

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]
    branches: [main]

jobs:
  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker

  csscomb:
    runs-on: ubuntu-latest
    needs: editorconfig
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - run: |
          npm init -y
          npm install csscomb --global
          csscomb css

  phpcs:
    runs-on: ubuntu-latest
    needs: csscomb
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.3'
          coverage: none
          tools: composer, cs2pr

      - name: Get Composer cache directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
          composer global config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true

      - name: Setup cache
        uses: pat-s/always-upload-cache@v3.0.11
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Run phpcs
        run: |
          composer global require drupal/coder
          composer global show -P
          composer phpcs
