name: Lint

on:
  workflow_dispatch:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Gitea Actions flag
        run: echo "RUNNING_ON_GITEA=${{ env.GITEA_ACTIONS || 'false' }}" >> $GITHUB_OUTPUT
        id: gitea_flag

      - uses: actions/checkout@v4
        if: ${{ steps.gitea_flag.outputs.RUNNING_ON_GITEA != 'true' }}

      - uses: editorconfig-checker/action-editorconfig-checker@main
        if: ${{ steps.gitea_flag.outputs.RUNNING_ON_GITEA != 'true' }}

      - run: editorconfig-checker
        if: ${{ steps.gitea_flag.outputs.RUNNING_ON_GITEA != 'true' }}

  csscomb:
    runs-on: ubuntu-latest
    needs: editorconfig
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '14.x'
      - run: |
          npm init -y
          npm install csscomb --global
          csscomb css

  phpcs:
    runs-on: ubuntu-latest
    needs: csscomb
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none
          tools: composer, cs2pr

      - name: Get Composer cache directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
          composer global config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true

      - name: Setup cache
        uses: pat-s/always-upload-cache@v3.0.11
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Run phpcs
        run: |
          composer global require drupal/coder
          composer global show -P
          composer phpcs
